name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Fish
        uses: fish-shop/install-fish-shell@v2

      - name: Indent check
        uses: fish-shop/indent-check@v2

      - name: Syntax check
        uses: fish-shop/syntax-check@v2
        with:
          pattern: "functions/*.fish conf.d/*.fish"

      - name: Install plugin
        uses: fish-shop/install-plugin@v2
        with:
          plugin-manager: fisher
          plugins: .

      - name: Test plugin files are valid
        run: |
          fish -c "
            # Test that abbreviation files can be sourced without errors
            source functions/abbr.fish
            echo 'Abbreviation file loaded successfully'
            
            # Test that conf.d file has valid syntax (skip interactive check)
            fish -c 'set -l original_status (status is-interactive); source conf.d/jj.fish; true'
            echo 'Configuration file is valid'
          "
